# Generated by Django 5.0.2 on 2024-05-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_actuator_actuator_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='actuator',
            name='actuator_type',
            field=models.CharField(choices=[('thermostat', 'Smart Thermostat'), ('humidifier', 'Ultrasonic Humidifier'), ('humidifier', 'Evaporative Humidifier'), ('air conditioner', 'Smart Air Conditioner'), ('fan', 'Smart Ceiling Fan'), ('fan', 'Portable Smart Fan'), ('heater', 'Electric Heater'), ('heater', 'Radiant Heater'), ('light', 'Smart Bulb'), ('light', 'Smart LED Strip'), ('water valve', 'Smart Water Valve'), ('water valve', 'Motorized Ball Valve'), ('switch', 'Smart Switch'), ('switch', 'Relay Module')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_types',
            field=models.CharField(choices=[('temperature', 'DHT11'), ('temperature', 'DHT22'), ('temperature', 'DS18B20'), ('temperature', 'LM35'), ('humidity', 'DHT22'), ('humidity', 'HIH-4000'), ('humidity', 'SHT31'), ('air quality', 'Grove - Air Quality Sensor v1.3'), ('air quality', 'MQ-135'), ('air quality', 'CCS811'), ('light', 'TSL2561'), ('light', 'BH1750'), ('motion', 'PIR Sensor'), ('motion', 'HC-SR501'), ('pressure', 'BMP280'), ('pressure', 'BME680'), ('sound', 'KY-038'), ('sound', 'Grove - Sound Sensor'), ('proximity', 'VL53L0X'), ('proximity', 'Ultrasonic Sensor HC-SR04')], max_length=50),
        ),
    ]
