# Generated by Django 5.0.2 on 2024-05-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='value',
        ),
        migrations.AddField(
            model_name='reading',
            name='airquality_value',
            field=models.FloatField(default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='humidty_value',
            field=models.FloatField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='temp_value',
            field=models.FloatField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
